apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-account
  namespace: toggle
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::047719652987:role/tc-eks-dynamo-prod-irsa