apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::047719652987:role/tc-eks-sqs-prod-irsa
  name: evaluation-service-account
  namespace: toggle
---
apiVersion: v1
data:
  FLAG_SERVICE_URL: http://flags-service:8002
  PORT: "8004"
  TARGETING_SERVICE_URL: http://targeting-service:8003
kind: ConfigMap
metadata:
  name: evaluation-configmap
  namespace: toggle
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: toggle
spec:
  ports:
    - port: 8004
      protocol: TCP
      targetPort: 8004
  selector:
    app: evaluation
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evaluation
  name: evaluation-deployment
  namespace: toggle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: evaluation-configmap
            - secretRef:
                name: evaluation-secret
            - secretRef:
                name: aws-session-creds
          image: 047719652987.dkr.ecr.us-east-1.amazonaws.com/tech-challenge/evaluation-image:0.0.0-lab.17-62d79f0
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8004
            periodSeconds: 20
            timeoutSeconds: 5
          name: evaluation-container
          ports:
            - containerPort: 8004
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /health
              port: 8004
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 8
          resources:
            limits:
              cpu: 500m
              memory: 192Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: 8004
            periodSeconds: 5
      serviceAccountName: evaluation-service-account
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evaluation-hpa
  namespace: toggle
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evaluation-deployment
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: evaluation-secret
  namespace: toggle
spec:
  data:
    - remoteRef:
        key: tc-evaluation-app-prod
        property: SERVICE_API_KEY
      secretKey: SERVICE_API_KEY
    - remoteRef:
        key: tc-evaluation-app-prod
        property: REDIS_URL
      secretKey: REDIS_URL
    - remoteRef:
        key: tc-evaluation-app-prod
        property: AWS_SQS_URL
      secretKey: AWS_SQS_URL
    - remoteRef:
        key: tc-evaluation-app-prod
        property: AWS_REGION
      secretKey: AWS_REGION
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    creationPolicy: Owner
    name: evaluation-secret
